### ISSUE TITLE
Bug: invalid MIS

### ISSUE THREAD

**Issue by teaguetomesh** [Hespian/CutBranching#1]
Hi, I was attempting to use your algorithm to find a MIS for the following graph:

![Screen Shot 2021-03-03 at 5 08 56 PM](https://user-images.githubusercontent.com/20692050/109879103-25935e00-7c43-11eb-83e4-074bde8dc699.png)

I stored the graph in a file `Input/G41.txt`:
[G41.txt](https://github.com/Hespian/CutBranching/files/6079501/G41.txt)

When I execute: `./MIS Input Output`

I get the following output: `Instance: G41.txt branches: 0 time: 2.7895e-05 MIS size: -6`

However, for this graph I believe the optimal MIS size is 4. Did I format the graph file incorrectly?

Thanks for all your help

**Comment by Hespian** [comment]
Thanks for your bug report! Apparently we reported the vertex cover size (times -1) instead of the independent set size. That should be fixed now.
