### ISSUE TITLE
Build error on MacOS (arm64)

### ISSUE THREAD

**Issue by MarkAureli** [Hespian/CutBranching#2]
Hey, I encountered the following problem when trying to build the module. I precisely followed the steps specified in the README. However, upon executing make (within the build directory), I get the compile error that 
```
/my/home/path/CutBranching/algo/branch_and_reduce_algorithm.h:33:10: fatal error:  '../Metis/include/metis.h' file not found
```
I am compiling on an arm64 architecture, but I doubt that this causes this issue.

**Comment by Hespian** [comment]
I also don't see metis in the repo. @ChristianSchorr what is metis used for? Is it only for the nested dissection branching? In that case, as this branching strategy didn't yield very strong results, we could probably just disable the code using metis?

**Comment by MarkAureli** [comment]
Many thanks for the early reply, wasn't expecting such a quick answer.
In case you don't want to update your repository, can you provide me with an easy fix?

**Comment by ChristianSchorr** [comment]
Hi, thanks for pointing out this problem! We initially used Metis to compute nested dissections. We eventually switched to [InertialFlowCutter](https://github.com/kit-algo/InertialFlowCutter) for this purpose. I have commented out the vestiges of the Metis-related code, which solves the issue (1da2199471668fcb25b7a06ca8beca92e06af5ed).

Note that if you want to use nested dissection branching, you need to set the `USE_IFC` option to `ON` in CMakeLists.txt as described in the README.
